from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any

import psycopg
from psycopg import sql
from psycopg.types.json import Json


@dataclass(frozen=True)
class DbCfg:
    host: str
    port: int
    dbname: str
    user: str
    password: str


SOURCE = DbCfg(
    host="localhost",
    port=5432,
    dbname="postgres",
    user="postgres",
    password="2026",
)

TARGET = DbCfg(
    host="192.168.10.4",
    port=5432,
    dbname="banco_prod",
    user="postgres",
    password="Acesso@123",
)

SOURCE_SCHEMA = "public"
TARGET_SCHEMA = "modelagem"
BATCH_SIZE = 1000


def connect(cfg: DbCfg) -> psycopg.Connection:
    return psycopg.connect(
        host=cfg.host,
        port=cfg.port,
        dbname=cfg.dbname,
        user=cfg.user,
        password=cfg.password,
    )


def qident(name: str) -> sql.Identifier:
    return sql.Identifier(name)


def normalize_default_expr(default_expr: str | None, target_schema: str) -> tuple[str | None, str | None]:
    if not default_expr:
        return None, None
    expr = default_expr.strip()
    m = re.search(r"nextval\('([^']+)'::regclass\)", expr, flags=re.IGNORECASE)
    if not m:
        return expr, None
    seq_ref = m.group(1)
    seq_name = seq_ref.split(".")[-1]
    mapped = f"nextval('{target_schema}.{seq_name}'::regclass)"
    return mapped, seq_name


def fetch_source_tables(cur: psycopg.Cursor, schema: str) -> list[str]:
    cur.execute(
        """
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = %s
          AND table_type = 'BASE TABLE'
        ORDER BY table_name
        """,
        (schema,),
    )
    return [r[0] for r in cur.fetchall()]


def fetch_columns(cur: psycopg.Cursor, schema: str, table: str) -> list[dict[str, Any]]:
    cur.execute(
        """
        SELECT
            a.attnum,
            a.attname AS column_name,
            pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
            a.attnotnull AS not_null,
            a.attidentity AS identity_kind,
            pg_get_expr(ad.adbin, ad.adrelid) AS default_expr
        FROM pg_attribute a
        JOIN pg_class c ON c.oid = a.attrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
        WHERE n.nspname = %s
          AND c.relname = %s
          AND a.attnum > 0
          AND NOT a.attisdropped
        ORDER BY a.attnum
        """,
        (schema, table),
    )
    rows = cur.fetchall()
    out: list[dict[str, Any]] = []
    for row in rows:
        out.append(
            {
                "column_name": row[1],
                "data_type": row[2],
                "not_null": bool(row[3]),
                "identity_kind": row[4] or "",
                "default_expr": row[5],
            }
        )
    return out


def fetch_pk_columns(cur: psycopg.Cursor, schema: str, table: str) -> list[str]:
    cur.execute(
        """
        SELECT a.attname
        FROM pg_index i
        JOIN pg_class c ON c.oid = i.indrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        JOIN unnest(i.indkey) WITH ORDINALITY AS k(attnum, ord) ON TRUE
        JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = k.attnum
        WHERE n.nspname = %s
          AND c.relname = %s
          AND i.indisprimary
        ORDER BY k.ord
        """,
        (schema, table),
    )
    return [r[0] for r in cur.fetchall()]


def table_exists(cur: psycopg.Cursor, schema: str, table: str) -> bool:
    cur.execute(
        """
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = %s
          AND table_name = %s
          AND table_type = 'BASE TABLE'
        LIMIT 1
        """,
        (schema, table),
    )
    return cur.fetchone() is not None


def fetch_target_columns(cur: psycopg.Cursor, schema: str, table: str) -> set[str]:
    cur.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = %s
          AND table_name = %s
        """,
        (schema, table),
    )
    return {r[0] for r in cur.fetchall()}


def build_column_fragment(col: dict[str, Any], target_schema: str) -> tuple[sql.SQL, str | None]:
    name = col["column_name"]
    data_type = col["data_type"]
    not_null = col["not_null"]
    identity_kind = col["identity_kind"]
    default_expr = col["default_expr"]

    parts = [sql.Identifier(name), sql.SQL(data_type)]
    sequence_to_create: str | None = None

    if identity_kind == "a":
        parts.append(sql.SQL("GENERATED ALWAYS AS IDENTITY"))
    elif identity_kind == "d":
        parts.append(sql.SQL("GENERATED BY DEFAULT AS IDENTITY"))
    else:
        mapped_default, seq_name = normalize_default_expr(default_expr, target_schema)
        if seq_name:
            sequence_to_create = seq_name
        if mapped_default:
            parts.append(sql.SQL("DEFAULT " + mapped_default))

    if not_null:
        parts.append(sql.SQL("NOT NULL"))

    return sql.SQL(" ").join(parts), sequence_to_create


def ensure_target_table(
    cur_tgt: psycopg.Cursor,
    table: str,
    source_columns: list[dict[str, Any]],
    pk_columns: list[str],
) -> None:
    exists = table_exists(cur_tgt, TARGET_SCHEMA, table)

    if not exists:
        col_defs: list[sql.SQL] = []
        seqs: set[str] = set()
        for col in source_columns:
            col_sql, seq_name = build_column_fragment(col, TARGET_SCHEMA)
            col_defs.append(col_sql)
            if seq_name:
                seqs.add(seq_name)

        for seq_name in sorted(seqs):
            cur_tgt.execute(
                sql.SQL("CREATE SEQUENCE IF NOT EXISTS {}.{}").format(
                    qident(TARGET_SCHEMA),
                    qident(seq_name),
                )
            )

        table_items = list(col_defs)
        if pk_columns:
            table_items.append(
                sql.SQL("PRIMARY KEY ({})").format(
                    sql.SQL(", ").join(sql.Identifier(c) for c in pk_columns)
                )
            )

        cur_tgt.execute(
            sql.SQL("CREATE TABLE IF NOT EXISTS {}.{} ({})").format(
                qident(TARGET_SCHEMA),
                qident(table),
                sql.SQL(", ").join(table_items),
            )
        )
        return

    # Tabela já existe: adiciona apenas colunas faltantes (sem remover nem alterar existentes)
    target_cols = fetch_target_columns(cur_tgt, TARGET_SCHEMA, table)
    for col in source_columns:
        col_name = col["column_name"]
        if col_name in target_cols:
            continue
        col_sql, seq_name = build_column_fragment(col, TARGET_SCHEMA)
        if seq_name:
            cur_tgt.execute(
                sql.SQL("CREATE SEQUENCE IF NOT EXISTS {}.{}").format(
                    qident(TARGET_SCHEMA),
                    qident(seq_name),
                )
            )
        cur_tgt.execute(
            sql.SQL("ALTER TABLE {}.{} ADD COLUMN IF NOT EXISTS {}").format(
                qident(TARGET_SCHEMA),
                qident(table),
                col_sql,
            )
        )


def row_count(cur: psycopg.Cursor, schema: str, table: str) -> int:
    cur.execute(
        sql.SQL("SELECT COUNT(*) FROM {}.{}").format(
            qident(schema),
            qident(table),
        )
    )
    return int(cur.fetchone()[0])


def sync_table_data(
    cur_src: psycopg.Cursor,
    cur_tgt: psycopg.Cursor,
    table: str,
    source_columns: list[dict[str, Any]],
    pk_columns: list[str],
) -> tuple[int, int, int]:
    columns = [c["column_name"] for c in source_columns]
    json_col_indexes = {
        idx
        for idx, c in enumerate(source_columns)
        if str(c.get("data_type", "")).lower() in {"json", "jsonb"}
    }

    src_total = row_count(cur_src, SOURCE_SCHEMA, table)
    tgt_before = row_count(cur_tgt, TARGET_SCHEMA, table)

    select_stmt = sql.SQL("SELECT {} FROM {}.{}").format(
        sql.SQL(", ").join(sql.Identifier(c) for c in columns),
        qident(SOURCE_SCHEMA),
        qident(table),
    )
    cur_src.execute(select_stmt)

    insert_base = sql.SQL("INSERT INTO {}.{} ({}) VALUES ({})").format(
        qident(TARGET_SCHEMA),
        qident(table),
        sql.SQL(", ").join(sql.Identifier(c) for c in columns),
        sql.SQL(", ").join(sql.Placeholder() for _ in columns),
    )

    if pk_columns:
        insert_stmt = insert_base + sql.SQL(" ON CONFLICT ({}) DO NOTHING").format(
            sql.SQL(", ").join(sql.Identifier(c) for c in pk_columns)
        )
    else:
        insert_stmt = insert_base

    while True:
        rows = cur_src.fetchmany(BATCH_SIZE)
        if not rows:
            break
        if json_col_indexes:
            prepared_rows = []
            for row in rows:
                mutable = list(row)
                for idx in json_col_indexes:
                    val = mutable[idx]
                    if isinstance(val, (dict, list)):
                        mutable[idx] = Json(val)
                prepared_rows.append(tuple(mutable))
            cur_tgt.executemany(insert_stmt, prepared_rows)
        else:
            cur_tgt.executemany(insert_stmt, rows)

    tgt_after = row_count(cur_tgt, TARGET_SCHEMA, table)
    inserted = max(tgt_after - tgt_before, 0)
    return src_total, tgt_before, inserted


def main() -> None:
    print("== MIGRACAO NAO-DESTRUTIVA (local public -> remoto modelagem) ==")
    with connect(SOURCE) as src_conn, connect(TARGET) as tgt_conn:
        src_conn.autocommit = False
        tgt_conn.autocommit = False

        with src_conn.cursor() as cur_src, tgt_conn.cursor() as cur_tgt:
            cur_tgt.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(qident(TARGET_SCHEMA)))

            tables = fetch_source_tables(cur_src, SOURCE_SCHEMA)
            print(f"tabelas_origem={len(tables)}")

            report: list[tuple[str, int, int, int]] = []
            for table in tables:
                source_columns = fetch_columns(cur_src, SOURCE_SCHEMA, table)
                pk_cols = fetch_pk_columns(cur_src, SOURCE_SCHEMA, table)
                ensure_target_table(cur_tgt, table, source_columns, pk_cols)
                tgt_conn.commit()

                src_total, tgt_before, inserted = sync_table_data(cur_src, cur_tgt, table, source_columns, pk_cols)
                tgt_conn.commit()
                report.append((table, src_total, tgt_before, inserted))
                print(
                    f"[ok] {table}: origem={src_total} | destino_antes={tgt_before} | inseridos={inserted}"
                )

            print("== RESUMO ==")
            total_inserted = 0
            for table, src_total, tgt_before, inserted in report:
                total_inserted += inserted
                print(
                    f"{table}: origem={src_total}, destino_antes={tgt_before}, inseridos={inserted}"
                )
            print(f"total_inseridos={total_inserted}")


if __name__ == "__main__":
    main()
